# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Extract cats
              run: cd media && unzip -P ${{ secrets.CAT_ASSETS_PASSWORD }} cat.zip
              if: github.ref == 'refs/heads/main'
            - run: npm ci
            - run: npm run compile
            - run: npm run lint
            - name: Run unit and integration tests
              uses: GabrielBB/xvfb-action@v1.6
              with:
                run: npm run test
            - name: Run coverage
              uses: GabrielBB/xvfb-action@v1.6
              continue-on-error: true
              with:
                run: npm run test:coverage
            - uses: codecov/codecov-action@v4
              with:
                directory: ./coverage
                token: ${{ secrets.CODECOV_TOKEN }}
            
            - name: Package VSIX
              run: npm install -g vsce && vsce package
            - uses: actions/upload-artifact@v4
              with:
                path: "*.vsix"
